"""
📄 CV GENERATOR MODULE
======================
Generates professional, aesthetically pleasing HTML CVs.
"""

import os
from datetime import datetime
import json
from pathlib import Path

class CVGenerator:
    """Generates professional HTML CVs"""
    
    def __init__(self):
        self.styles = self._get_styles()
        
    def generate_cv(self, user_data: dict, output_file: str = "generated_cv.html"):
        """Generate HTML CV from user data"""
        
        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{user_data.get('name', 'CV')} - Curriculum Vitae</title>
            <style>
                {self.styles}
            </style>
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">
        </head>
        <body>
            <div class="cv-container">
                <header class="cv-header">
                    <div class="header-content">
                        <h1>{user_data.get('name', '')}</h1>
                        <p class="tagline">{user_data.get('title', '')}</p>
                        <div class="contact-info">
                            <span>📧 {user_data.get('email', '')}</span>
                            <span>📱 {user_data.get('phone', '')}</span>
                            <span>📍 {user_data.get('location', '')}</span>
                            <span>🔗 <a href="{user_data.get('linkedin', '#')}">LinkedIn</a></span>
                            <span>💻 <a href="{user_data.get('portfolio', '#')}">Portfolio</a></span>
                        </div>
                    </div>
                </header>

                <main class="cv-main">
                    <section class="section summary">
                        <h2>Professional Summary</h2>
                        <p>{user_data.get('summary', '')}</p>
                    </section>

                    <section class="section experience">
                        <h2>Experience</h2>
                        {self._format_experience(user_data.get('experience', []))}
                    </section>

                    <section class="section education">
                        <h2>Education</h2>
                        {self._format_education(user_data.get('education', []))}
                    </section>

                    <section class="section skills">
                        <h2>Skills</h2>
                        <div class="skills-grid">
                            {self._format_skills(user_data.get('skills', []))}
                        </div>
                    </section>
                    
                    <section class="section projects">
                        <h2>Key Projects</h2>
                        {self._format_projects(user_data.get('projects', []))}
                    </section>
                </main>
                
                <footer class="cv-footer">
                    <p>Generated by InternMailer AI • {datetime.now().strftime('%B %Y')}</p>
                </footer>
            </div>
        </body>
        </html>
        """
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
            
        print(f"✅ CV generated successfully: {output_file}")
        return output_file

    def _format_experience(self, experience_list):
        html = ""
        for exp in experience_list:
            html += f"""
            <div class="job-entry">
                <div class="job-header">
                    <h3>{exp.get('role', '')}</h3>
                    <span class="company">{exp.get('company', '')}</span>
                    <span class="date">{exp.get('duration', '')}</span>
                </div>
                <ul class="job-details">
                    {''.join(f'<li>{item}</li>' for item in exp.get('details', []))}
                </ul>
            </div>
            """
        return html

    def _format_education(self, education_list):
        html = ""
        for edu in education_list:
            html += f"""
            <div class="edu-entry">
                <h3>{edu.get('degree', '')}</h3>
                <span class="school">{edu.get('school', '')}</span>
                <span class="date">{edu.get('year', '')}</span>
                <p class="grade">{edu.get('grade', '')}</p>
            </div>
            """
        return html

    def _format_skills(self, skills_list):
        return ''.join(f'<span class="skill-tag">{skill}</span>' for skill in skills_list)

    def _format_projects(self, projects_list):
        html = ""
        for proj in projects_list:
            html += f"""
            <div class="project-entry">
                <h3>{proj.get('name', '')}</h3>
                <p>{proj.get('description', '')}</p>
                <div class="tech-stack">
                    {''.join(f'<span class="tech-tag">{tech}</span>' for tech in proj.get('tech', []))}
                </div>
            </div>
            """
        return html

    def _get_styles(self):
        return """
        :root {
            --primary: #2563eb;
            --text: #1f2937;
            --text-light: #6b7280;
            --bg: #ffffff;
            --bg-alt: #f3f4f6;
        }
        
        body {
            font-family: 'Inter', sans-serif;
            line-height: 1.6;
            color: var(--text);
            background: #e5e7eb;
            margin: 0;
            padding: 40px 0;
        }
        
        .cv-container {
            max-width: 800px;
            margin: 0 auto;
            background: var(--bg);
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            overflow: hidden;
        }
        
        .cv-header {
            background: var(--primary);
            color: white;
            padding: 40px;
        }
        
        .cv-header h1 {
            margin: 0;
            font-size: 2.5rem;
            font-weight: 700;
        }
        
        .tagline {
            font-size: 1.2rem;
            opacity: 0.9;
            margin-top: 5px;
        }
        
        .contact-info {
            margin-top: 20px;
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
            font-size: 0.9rem;
        }
        
        .contact-info a {
            color: white;
            text-decoration: none;
            border-bottom: 1px solid rgba(255,255,255,0.5);
        }
        
        .cv-main {
            padding: 40px;
        }
        
        .section {
            margin-bottom: 30px;
        }
        
        h2 {
            color: var(--primary);
            border-bottom: 2px solid var(--bg-alt);
            padding-bottom: 10px;
            margin-bottom: 20px;
            font-size: 1.2rem;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        .job-entry, .project-entry {
            margin-bottom: 25px;
        }
        
        .job-header {
            display: flex;
            justify-content: space-between;
            align-items: baseline;
            margin-bottom: 10px;
        }
        
        .job-header h3 {
            margin: 0;
            font-size: 1.1rem;
            font-weight: 600;
        }
        
        .company, .school {
            font-weight: 500;
            color: var(--text-light);
        }
        
        .date {
            font-size: 0.9rem;
            color: var(--text-light);
        }
        
        .skills-grid {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
        }
        
        .skill-tag {
            background: var(--bg-alt);
            padding: 5px 12px;
            border-radius: 15px;
            font-size: 0.9rem;
            font-weight: 500;
        }
        
        .tech-tag {
            font-size: 0.8rem;
            color: var(--primary);
            margin-right: 10px;
        }
        
        .cv-footer {
            background: var(--bg-alt);
            text-align: center;
            padding: 20px;
            font-size: 0.8rem;
            color: var(--text-light);
        }
        
        @media print {
            body {
                background: white;
                padding: 0;
            }
            .cv-container {
                box-shadow: none;
                max-width: 100%;
            }
        }
        """

if __name__ == "__main__":
    # Test data
    test_data = {
        "name": "Anamay Tripathy",
        "title": "Data Science Engineering Student",
        "email": "tripathy.anamay23@gmail.com",
        "phone": "+91-9877454747",
        "location": "Manipal, India",
        "linkedin": "linkedin.com/in/anamay",
        "portfolio": "anamay.vercel.app",
        "summary": "Passionate Data Science student with expertise in Machine Learning, AI, and Full Stack Development. Proven track record of leading technical teams and delivering impactful projects.",
        "experience": [
            {
                "role": "Technical Head",
                "company": "YaanBarpe",
                "duration": "2023 - Present",
                "details": [
                    "Leading 12 developers creating sustainable tech solutions.",
                    "Developed ML-powered waste management systems achieving 34% efficiency improvement."
                ]
            }
        ],
        "education": [
            {
                "degree": "B.Tech Data Science Engineering",
                "school": "MIT Manipal",
                "year": "2021 - 2025",
                "grade": "CGPA: 8.5/10"
            }
        ],
        "skills": ["Python", "TensorFlow", "React", "SQL", "AWS", "Docker"],
        "projects": [
            {
                "name": "InternMailer",
                "description": "Automated internship application system.",
                "tech": ["Python", "AI", "Automation"]
            }
        ]
    }
    
    generator = CVGenerator()
    generator.generate_cv(test_data)
